aliyun/plugsched

- src/main.c
Since all fn_ptrs are jumped to corresponding functions with __mod
prefix, there is no need to re-register SCHED_SOFTIRQ again.
> src: remove SCHED_SOFTIRQ re-registration logic

- Dockerfile
Choose "Plus" yum repo for gcc-python-plugin, which is disabled by default
in Anolis OS.
Force compile pyyaml with libyaml-devel, otherwise we can't import CLoader.
> contrib: Fix two bugs in Dockerfile when working with Anolis OS

- cli.py
It is not necessary to verify build dependencies for extracting src, and python2 and python3 are distinguished in anolis OS, so we need to specify the python version.
> cli.py: fix the bug of extract_src command

- Dockerfile
Compiling pyyaml requires python2-devel
Fixes: eb100b36ef50 ("contrib: force compile pyyaml with libyaml-devel")
> contrib: install python2-devel before compiling pyyaml

- README.md
- README_zh.md
This question is not recognized by markdown as bold because of needless
space. This | is a full-width character by accident, and users can't
excecute it as a pipe.
> docs: fix format of README

- LICENSE
This file is unimportant, as long as we have LICENSE.BSD and LICENSE.GPLv2.
Remove it so Github can correctly identify only these two LICENSE files,
rather than one more unknown LICENSE file.
> docs: delete LICENSE 

- tests/test_cpu_throttle/assert
- tests/test_domain_rebuild/assert
- tests/test_public_var/assert
- tests/test_sched_syscall/assert
- tests/test_var_uniformity/assert
Add SPDX information for tests:
1. test_cpu_throttle
2. test_domain_rebuild
3. test_public_var
4. test_sched_syscall
5. test_var_uniformity
Signed-off-by: Xuchun Shang <xuchun.shang@linux.alibaba.com>
> src: add SPDX information

- Dockerfile.aarch64
- Dockerfile.x86_64
Optimize the method to get pip3, that is, using yum install python3-pip.
And the yum way will get the pyyaml with libyaml by default, so the
--with-libyaml parameter is removed.
> contrib: replace wget with yum to get pip3

- cli.py
Commit 2ed82330(src: fix the bug kernel modules don't inflect outsiders)
can generate the new vmlinux and Modules.symvers files after the collect
stage in the init process, which can rewrite these two files copied from
kernel-devel and kernel-debuginfo and we can not get the right symbols'
informations of the vmlinux.
I try to modify the Makefile to find a way that can compile kernel and
modules without generating the vmlinux and Modules.symvers, but failed.
So, copying the vmlinux and Modules.symvers files from kernel-devel and
kernel-debuginfo after the collect stage is a simple way to fix the
issue above, and then the two files can cover the generated files.
Fixes: 2ed82330 (src: fix the bug kernel modules don't inflect outsiders)
Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>
> cli: put off copying the vmlinux and Module.symver files

- src/helper.h
- src/mempool.h
Functions and variables in headers of /src are only used by plugsched
itself, so they should be static, to avoid conflicts with kernel source
code. (e.g. bsearch)
Signed-off-by: Tianchen Ding <dtcccc@linux.alibaba.com>
> src: make functions and variables in headers static

- Dockerfile.x86_64
Because the gcc-python-plugin-0.17-1.2 package is built in anolis
8.6 and the yum Plus repo is shared between 8.6 and 8.4, the
gcc-python-plugin-0.17-1.2 can not work in anolis8.4. And the Anolis8.4
is no longer maintained, so I migrate the base docker image from 8.4 to
8.6 and the new docker image will be rolled out at next release.
I have tested the plugsched in the new docker image which can not afect
the exist system.
Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>
> contrib: migrate anolis base docker image from 8.4 to 8.6

- cli.py
- configs/4.19/dynamic_springboard.patch
- src/Makefile
- src/Makefile.plugsched
- tools/springboard_search.sh
The stack balancing relies on the frame pointer register of __schedule function now. But frame pointer register may be optimized for example in kernel 5.10. So I use another way.
The core.c will be compiled twice. The first is to get the stack size of __schedule and the value will be used for the second compilation by passing macro -DSTACKSIZE_MOD. The new way of stack balancing is following:
add sp stack_size_of_mod
sub sp stack_size_of_vmlinux
> remove frame pointer register for stack balancing for x86

- boundary/extract.py
- cli.py
It fixes the invalid header path problem caused by source files in different directories. e.g.
A file is at kernel/xxx/yyy.c
#include "zzz.h" -> this means include kernel/xxx/zzz.h
however, after extraction, yyy.c will be at kernel/sched/mod/yyy.c
#include "../zzz.h" -> will try to look for kernel/sched/zzz.h, but
it not exists!
> Move the post-init fix_up logic to the extraction stage

- tests/test_var_uniformity/assert
In some kernel version, the sched_rt_global_constraints will restrict
the ratio rt_runtime/rt_period which leads to test failure. 
Signed-off-by: Xuchun Shang <xuchun.shang@linux.alibaba.com>
> test: remove the var test of sched_rt_runtime_us

- tests/test_sched_syscall/assert
There exists a situation that /sys/fs/cgroup/cpuset/test may be
freed twice(test fail) which leads to execution error.
Signed-off-by: Xuchun Shang <xuchun.shang@linux.alibaba.com>
> tests: fix double free of cgroup file

- src/main.c
- tools/springboard_search.sh
There are some compilation errors when building the scheduler module
for arm64 kernel-4.19. See the first error log:
/root/scheduler/kernel/sched/mod//main.c: In function
'disable_stack_protector':
/root/scheduler/kernel/sched/mod//main.c:137:35: error:
'STACK_PROTECTOR' undeclared (first use in this function)
137 |  void *addr = __orig___schedule + STACK_PROTECTOR;
|                                   ^~~~~~~~~~~~~~~
/root/scheduler/kernel/sched/mod//main.c:137:35: note: each
undeclared identifier is reported only once for each function it
appears in /root/scheduler/kernel/sched/mod//main.c:139:14: error:
'STACK_PROTECTOR_LEN' undeclared (first use in this function)
139 |  for (i=0; i<STACK_PROTECTOR_LEN; i++, addr+=4)
|              ^~~~~~~~~~~~~~~~~~
The reason of this error is that the …
> tools: fix some compilation errors for kernel 4.19 aarch64

- tests/bundles/ci
- tests/test_mem_pressure/assert
We pin the memory with /dev/shm, because it has these advantages,
- memory won't be freed as a result of OOM (better than with malloc)
- It pins memory very quickly (better than with malloc)
- It pins discontinuous virtual memory (better than with hugepage)
We pin 60% of the currently available memory. And we repeat this process
until only 50MB memory left.
If rpm, insmod, we exit the test early and gives an warning, but don't
fail the test.
> tests: add a memory pressure test

- src/Makefile.plugsched
This patch fixes two bugs of Makefile for kernel 5.10, see the commit log for details.
> src: fix the compilation errors for kernel-5.10

- boundary/analyze.py
- boundary/collect.py
- configs/4.19/boundary.yaml
- configs/5.10/boundary.yaml
- src/sched_rebuild.c
W/ this patch, the number of callbacks was reduced from 163 to 73.
If one variable is marked as 'force_private', we assume it doesn't
have data dependencies with vminux.
These are the callback functions left over:
cpu_files：   6
cpu_legacy_files： 19
cpu_cgrp_subsys： 8  （ref cpu_files, cpu_legacy_files）
timer callback： 6
sysctl： 6
cpu hotplug：4
CACHE_HEADER： 4
rt/dl balance_callback：4
> border: try to remove inside callback functions out of fn_ptr set

- boundary/analyze.py
- boundary/collect.py
- boundary/extract.py
- src/Makefile
- src/head_jump.h
- src/stack_check.h
- tools/symbol_resolve/symbol_resolve.cpp
In most languages, `function pointer` refers to variables that stores
addresses of functions, and `callback` refers to functions that are stored
in these variables. So we misused the term `function pointer`. `callback`
should be the right and conventional term.
This patch doesn't change any funcionality.
> src: change the term fnptr to callback

- boundary/analyze.py
border: forbid redirecting mangled functions
interface, callback or sidecar functions are to be redirected when loading
the module. But if these functions are mangled by GCC, they lose the
original semantics in general cases, because mangling usually happens when
optimzing for some special cases. Redirecting them will lead to bugs.
Moreover, GCC usually leaves an unmangled symbol in the binary as well,
making it look safe to redirect this unmangled symbol. But is not safe.
So in the analyze phase, we check if interface, callback or sidecar
functions are mangled. If they do, the analyzing fails.
> border: forbid redirecting mangled functions

- boundary/collect.py
- boundary/extract.py
- cli.py
More callbacks means rely more on gcc-python-plugin and harder to understand. Just like collect_fn/edge/struct, this PR moves variable info collection to final_work(). Meanwhile, the include_file() callback is not used for long time, it's time to remove it.
BTW, the private implemented function gcc.get_location() is abandoned.
> Reduce gcc callback

- boundary/analyze.py
Fix the inverted assert condition of redirecting mangled functions
Fixes: 447744cbc3a8 ("border: forbid redirecting mangled functions")
> border: fix "forbid redirecting mangled functions"

- src/sched_rebuild.c
The invalid array size causes sched_class to be incorrectly initialized,
then lead to kernel panic.
Fixes: 17f974e ("src: migrate sched_class for every task during
upgrade and rollback")
> src: fix kernel panic when loading scheduler.ko

- cli.py
To make debugging easier, print the original output message on
the screen.
> cli: print logging to stdio for better user experience

- src/main.c
- src/sched_rebuild.c
Commit 17f974e doesn't migrate sched_class for those tasks on
offlined cpus, such as idle task, stopper, and other per-cpu
kthread. Once offline cpu come back, both old and new sched_class
exists on system, which make scheduler puzzle.
Refer to the stack check for tasks on offline cpus, using the
same way to migrate sched_class.
Fixes: 17f974e ("src: migrate sched_class for every task during
upgrade and rollback")
> src: fix kernel panic during cpu hotplug test

- cli.py
Commit 2ed82330(src: fix the bug kernel modules don't inflect
outsiders) aims to fix the bug that the kernel modules cannot inflect
outsiders. It uses a conservative way that is compiling the entire
kernel (includes compiling kernel modules), which will generate the
new vmlinux and modules.symver and overwrite the orignal files copied
from kernel-debuginfo and kernel-devel. It's incorrect because the
build stage must reference orignal files.
So, commit a36efadb6(cli: put off copying the vmlinux and Module.symver
files) uses a workaround to fix the problem above.
Now, plugsched does not allow exported functions to be insiders(commit
https://github.com/aliyun/plugsched/commit/f1326f6335ce035b6b0e7e5ecd976ef33a98f9e3(border: remove exported functions from internal function set)).
So it is …
> Revert "cli: put off copying the vmlinux and Module.symver files"

- tools/springboard_search.sh
We search stackproctors by matching "<__schedule+OFFSET>" in the assembly,
where __schedule+OFFSET points to __stack_chk_fail.
11d1a5437a2c changes stack protector matching pattern from the last column
in the assembly to the 5th column. Because sometimes the jump instruction
used by stack protector is "b.ne", and b.ne has only one operator. But in
other cases, the instruction might be "cbnz", which has two operators.
To take both cases into account, we should check both the 5th and the 6th
column.
Fixes: 11d1a5437a2c ("tools: fix some compilation errors for kernel 4.19 aarch64")
==========
tools: use CONFIG_STACKPROTECTOR to indicate stack_chk_fail
As long as CONFIG_STACKPROTECTOR=y is present in the config file, we can be
sure that …
> tools: fix stackprotector search for aarch64

- boundary/collect.py
b9ff908f754e ("border: fix accessing union bug") fixes a bug when accessing
unnamed unions. However structs have exactly the same bug. So this patch
only checks whether,
1. Current ComponentRef's field is unnamed
2. Current ComponentRef's parent node (in the AST) is also a ComponentRef
and doesn't check whether the field is a union anymore.
> border: fix accessing unnamed struct bug

- boundary/analyze.py
- src/Makefile
The content of interface_callbacks file can be generated from  export_jump.h, so delete it to avoid maintaining two files.
> border: delete generated intermediate file 'interface_callbacks'

- src/Makefile
There's a potential problem. If we declare 'extern int __mod_xxx' in
main.c, but xxx doesn't exist in the module. Then __mod_xxx will refer
to xxx in vmlinux eventually.
This patch fix it by checking whether symbol xxx exist in scheduler
module.
Fixes: 00fa01c ("src: support for accessing static symbol with __mod_
prefix")
> src: fix invalid symbol reference when using __mod_ prefix

- boundary/extract.py
- configs/4.19/dynamic_springboard.patch
If we want to replace static functions, these functions in module must
not be optimized, or we will replace the entry with wrong jmp and cause
softlockup due to endless loop.
Add "__used" for static interface functions to prevent this.
> boundary: Prevent static interface functions from being optimized

- cli.py
- configs/4.19/dynamic_springboard.patch
- tools/springboard_search.sh
Once we have some kernels customized for plugsched. And we patched these
kernels with builtin springboards. Now that dynamic springboard is mature
enough, and doesn't require any customizing to the kernel, we can delete
the support for builtin springboard.
Also, this patch fixes the bug, that plugsched fails to work on some of
these kernels. Because currently, dynamic_springboard.patch is composed
of stack-pivot and springboard. And for these kernels, stack-pivot is
not applied as well. Without stack-pivot, the scheduler is easily broken.
> tools: stop supporting builtin springboard

- docs/Advanced-Features.md
From commit 016c777d ("border: reimplement sidecar with good design
and ease of use"), the sidecar code has changed dramatically. It's
required to tell users how to use sidecar.
> doc: update documentation for new sidecar implementation

- tools/springboard_search.sh
00a24b77eed7 ("tools: stop supporting builtin springboard") removes
<__schedule:> from asm_sequence, but still matches it when searching
stackprotector. Since the asm_sequence is disassembly of __schedule
function now, "start" variable can be safely deleted now. And after
deleting it, stackprotector searching works now.
Fixes: 00a24b77eed7 ("tools: stop supporting builtin springboard")
> tools: fix stack protector search

- boundary/collect.py
- src/Makefile.plugsched
Here are some major code style changes:
1. yapf -i border/analyze.py
2. write short comments for functions and classes;
3. limit all lines to a maximum of 79 characters;
4. delete unused import;
5. change names for some variable and function;
6. use single quotes when accessing dictionary keys;
> border: introduce PEP8 code style for collect.py

- boundary/analyze.py
If both strong and weak symbol are present in interface/callback/
sidecar function set, there will be two identical declaration string
in export_jump.h. Then will lead to compile error during build stage.
This patch fix it by keeping only one declaration string.
> border: keep only one if both strong and weak symbol exist

- src/main.c
clear_sched_state should use the currently running scheduler's functions to
perform clearing, instead of using the to-be-loaded scheduler's functions.
On the contrary, rebuild_sched_state should use the to-be-loaded scheduler.
The first CPU may run very slow, and after some other CPUs finish
redirecting scheduler functions. Then the first CPU violates the rule above.
> src: ensure redirect after clear_sched_state is done

- configs/4.19/dynamic_springboard.patch
- tools/springboard_search.sh
ROP is a hacker technique, which manipulates data on the stack directly. And this new method expolits vmlinux's call instruction like,
__schedule(scheduler)     __schedule(vmlinux)       __switch_to(vmlinux)
mov prev, rdi                mov prev, rdi
mov next, rsi                mov next, rsi
add diff-stack-size, rsp
jmp                   --->   call __switch_to  ---> push rbp
mov rax,*  <--.        ...
\       pop rbp
.---   ret
This solution is simpler than the previous one based on ROP.
Suggested-by: Erwei Deng <erwei@linux.alibaba.com>
> src: exploit vmlinux's call to avoid ROP

- boundary/analyze.py
Before this patch, dotdict.attr returns None when attr doesn't exist in dotdict, because "." operator is overwritten by "get" method. This behaviour hides bugs, and we don't benefit from this behavior at all. So this patch makes dotdict raising exceptions when attr doesn't exist, just likey "__getitem__" does.
By the way, fix a bug in "fn.publ", where "publ" should actually be "public". This bug is just hidden by this behaviour.
> border: forbid getting non-exist attr in dotdicts

- src/main.c
Here's a race condition of global_error. As we decrese cpu_finished before we assign error to global_error, the CPUs without error may not notice that error has occurred on other CPUs, which will cause panic. Here follows the timing diagram of this race condition.
CPU x			              CPU y
stack_check pass
cpu_finished dec	        stack_check fail
wait cpu_finished == 0	cpu_finished dec to 0
read global_error	         check cpu_finished ==0
normal path		         global_error = error
error handling
To fix this problem, we assign error to global_error before we decrese cpu_finished, so that we can guarantee that every CPU can get the correct global_error.
Signed-off-by: Cruz Zhao <CruzZhao@linux.alibaba.com>
> src: fix race condition of global_error

- src/head_jump.h
- src/main.c
- tests/run_test
- tests/test_mem_pressure/assert
Backoff when there's already ftrace on a function. Because if we insist on
overwritting function header, ftrace gets confused about its meta data and
may panic the kernel.
Ftrace and other similar infrastructures use call and jmp to do dynamic
patching. So we compare the first byte against 0xe8/0xe9 to see if we
should back off. For now, only x86-64 arch is supported.
> src: Check header modified by ftrace or sth before install

- boundary/extract.py
- src/main.c
- src/sched_rebuild.c
src: sync the state of sched_class variables in place
To mark struct sched_class as private, commit 17f974e migrates
sched_class for every task. However, there are race windows during
task fork and task exit. In both cases, sched_class are inconsistent,
will lead to kernel panic. E.G:
copy_process():
->sched_fork()-> init to old sched_class
... (might sleep)
... plugsched fail to switch sched_class, for the new task is
still not attacted to task_list.
->list_add_tail_rcu(&p->tasks, &init_task.tasks)
... using old sched_class!!!
do_exit():
->exit_notify()->release_task()->__exit_signal()->__unhash_process()
->list_del_rcu(&p->tasks)
... (maight sleep)
... plugsched fail to switch sched_class, for the dead task is
detached from task_list now.
->do_task_dead()->__schedule()->dequeue_task() …
> Fix sched class

- src/head_jump.h
- src/helper.h
- src/main.c
- src/sched_rebuild.c
- src/stack_check.h
I don't find a way to disable global write protect on arm64, so I use the fixmap again to fix this bug.
> Fix the compiling error of modification of sched_class on arm64

- boundary/analyze.py
There have an assert of sched_class structure to ensure that no outsider functions could call fair_sched_class.pick_next_task_fair().
But the sched_class variables are replaced by memcpy, so it is not necessary to keep this assert.
> Remove the assert of sched_class

- configs/5.10/boundary.yaml
Some members of sched_class are used by outsider functions which means that the boundary of kernel 5.10 is not complete. See the boundary_doc.yaml:
public_fields:
- dequeue_task
- enqueue_task
- set_next_task
- rq_online
- task_fork
- put_prev_task
- switched_from
- switched_to
- prio_changed
- rq_offline
So I make some adjustion of this boundary.
> Adjust the boundary of 5.10.

- boundary/analyze.py
- boundary/collect.py
- src/Makefile.plugsched
If there are a strong and a weak one, global_fn_dict will be overwritten because they're both public. Then get_func_decl_strs mistooks one of them as local symbol and fail to assert.
This bugfix takes the advantage of the fact: strong symbols are unique. (Although we hope weak symbols are unique too, but GCC seems to allow that)
So now "global_fn_dict" is actually "global_strong_fn_dict". And now we can divided all functions into 1) strong global 2) weak global 3) local. We use func_class to store all weak symbols. Then if a symbol is neither 1) nor 2), we know it's a local symbol.
Fixes: 89e09ed133e7 ("border: keep only one if both strong and weak symbol exist")
> border: fix "keep only one if both strong and weak symbol exist"

- configs/5.10/dynamic_springboard.patch
- src/Makefile
- src/main.c
- tools/springboard_search.sh
See the commit bfa04fc96da3e4252419dd3f7d2088efa3cfed97 <src: jump to vmlinux's call instead of pushing our return addres>
This commit adapets the springboard of kernel 5.10.
Why I delete the modification of the attribute of perpare_task_switch function is that, the frame pointer of __schedule in vmlinux becames not optimized. We cannot decide whether the frame pointer is optimized or not in vmlinux. Therefore, fixed stack frame pointer of __schedule function in vmlinux is more friendly to us.
> Update the dynamic_springboard.patch of 5.10.

- boundary/extract.py
In some kernels, some sched_class variables are not defined as const. 
And we failed to match the pattern. So we use a more stable one instead.
> border: fix sched_class renaming failing on some kernels

- tests/build_case
After installing some packages, containers refuses "podman exec -it". (See https://bugzilla.openanolis.cn/show_bug.cgi?id=1874). This causes CI running only the first test. Since the building process isn't interative and don't need a pseduo-terminal, we can safely remove these two options. Even though the root cause is not found, but at least it doesn't block us.
> tests: fix building in container

- src/mempool.h
In commit d3350c7460f4, we remove the "F" unexpectedly, which will cause error when mempool enabled.
> src: fix a typo of FIELD_TYPE

- boundary/extract.py
Replacing "static" without space may cause unexpected hurt to definitions whose name or type name has "static". e.g., struct static_key.
> border: fix an inaccurate replacement about static __used

- configs/5.10/boundary.yaml
Since commit ace8031099f9("sched/topology: Make local variables static"), sched_domains_tmpmask becomes local variable. And plugsched tags local variables as private variables. Besides, sched_domain is a component which is not covered by sched_rebuild technique. These two facts make sched_domains_tmpmask re-initialized to zero after loading the module.
However, sched_domains_tmpmask should be shared with the kernel because it contains running state information. Otherwise, when rebuilding the sched domain (e.g. when CPU hotplug), the kernel panics.
So put sched_domains_tmpmask (and sched_domains_tmpmask2) to extra public to fix this panic issue.
> config: fix panic when CPU hotplug on 5.10

- boundary/analyze.py
If weak symbols within the boundary are not linked into vmlinux, then they are classified as fake-global, because the real global symbols are the corresponding strong symbols that reside in other source files.
fake-global functions are added to scheduler-outsiders after inflection, so that their definitions can be removed. Also they should be removed from the insider set too.
This patch influences only confliction checking against kpatch.
Fixes: 259c48336f85("border: treat overriden weak symbols as outsiders")
> border: exclude not-linked weak functions from tainted functions

- configs/5.10/dynamic_springboard.patch
- tools/springboard_search.sh
- Fix stack pivot typo from STACKSIZE_SCHEDULE to STACKSIZE_VMLINUX.
- Fix springboard bug by passing register instead of memory to br insn.
- Fix stack chk
* Sometimes it jumps to 4 bytes before stack_chk_fail than right at it.
* Sometimes there are less than 12 callee-saved registers.
* When stack chk searching fails, error handling is not working.
> config: fix stack pivot, stack chk and springboard for 5.10 on aarch64

- configs/3.10/post_extract.patch
Update the following two points:
1. Update the stack check function to match the kernel 3.10.
2. Remove the assertion of stack layout because the __scheduler has been removed outside.
Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>
> border: update post_extract.patch of 3.10

- src/sched_rebuild.c
When a task goes to dying, there have a gap between removing from init_task list and releasing the task. In this case, we cannot find these tasks from init_task list, so that the rebuilder cannot deal with them including allocation and release memory.
The sched_cpu_dying gives us an idea that is using the pick_next_task to find these tasks. So it is safe.
Co-developed-by: Cruz Zhao <CruzZhao@linux.alibaba.com>
Signed-off-by: Erwei Deng <erwei@linux.alibaba.com>
> src: clean and rebuild the dying tasks

- tests/test_cpu_throttle/assert
It should be the instant cpu_util rather than the average cpu_util. Because we re-configure the system several times, and each time we should reset the counter.
> test: fix cpu_util algorithm in CPU throttle test

- configs/3.10/post_extract.patch
Because the kernel 3.10 does not have the rq_flags and clock_update_flags, it is necessary to adjust the rebuilding dying task logic.
> border: fix the logic of rebuilding dying task for 3.10

- configs/5.10/boundary.yaml
After boundary analysis, wake_up_idle_ht is a insider function. But it is called by the bottom of __schedule and this function of vmlinux will be called too. So it should be a interface function.
> border: add wake_up_idle_ht to interface for 5.10

- src/Makefile
- src/main.c
- src/sched_rebuild.c
For the symbol referenced, we have a rule:
If we reference module's symbols, we need to add the __mod_ prefix to the symbol, and if reference vmlinux's symbols, we need to add __orig_ prefix to the symbol.
In main.c and sched_rebuild.c, some symbol references do not follow the above rule. So I fixed them.
> src: use the right rule to reference symbols in module

- cli.py
The olddefconfig target can set the default value for any new configuration options that have been added to .config.
For the .config, it may add some new config for different compilation environment just like the CONFIG_GCC_PLUGIN, and if you do not specify a build target, the kbuild system will ask the user for the value of this configuration.
So I use the olddefconfig target to set these new configs to default value.
> Set the default value for the any new added configs.

- README.md
- README_zh.md
- cli.py
- module-contrib/scheduler.spec
- tests/build_case
The previous packaging process was very non-standard. First of all, copying external files during the rpmbuild prep stage was non-standard. The main work of the prep stage should be to extract the tar package and apply patches. Therefore, I moved all the externally copied files to the working directory.
Secondly, there were many external directories defined in the cli build command, which is also non-standard. All files used in the packaging process should be in the BUILD directory. Therefore, I deleted all the defined macros and directly modified the _builddir build directory, so that the rpmbuild build phase can directly enter the scheduler working directory for execution.
Lastly, I modified the location of the RPM package. It was not a good idea to place the RPM package in the …
> Standardized spec of scheduler package.

- src/main.c
sched_free_extrapad() is called between clear_sched_state() and rebuild_sched_state() in function __sync_sched_restore(). In function sched_free_extrapad(), free_percpu() may be called, which will result in queue_work_on() called, and a kwork will enqueue, between clear_sched_state() and rebuild_sched_state(), and it will enqueue again in function clear_sched_state(). In this case, cfs->h_nr_running will be wrong.
To fix this bug, we call sched_free_extrapad() later, after rebuild_sched_state().
Reported-by: Cruz Zhao <CruzZhao@linux.alibaba.com>
> src: fix the bug that tasks enqueue between clear_sched_state() and rebuild_sched_state()

- cli.py
- configs/5.10/dynamic_springboard.patch
- configs/5.10/dynamic_springboard_2.patch
Since ANCK 5.10-013, the function __schedule() has already __attribute__ ((optimize("no-omit-frame-pointer"))).
So there is no need to patch it. Split the patch into 2 parts, only patch the 2nd part on old kernel.
> config: split dynamic_springboard.patch into 2 parts
